dist: bionic  # Ubuntu 18.04 for new ruby version
language: python
python: 3.7
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb https://cran.rstudio.com/bin/linux/ubuntu bionic/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - rvm default
  - gem install json kramdown jekyll
install:
  - pip install pyyaml
script:
  - bundle config build.nokogiri --use-system-libraries
  - make lesson-check-all
  - make --always-make site
